apiVersion: v1
kind: Service
metadata:
  name: passwordpushersvc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: passwordpusherephemeral
  ports:
    - port: 5100
      targetPort: 5100