- hosts: "{{ (groups['cluster_nodes'] | shuffle)[1] }}"
  gather_facts: no
  tasks:
    - name: untaint nodes to allow pods to run on masters
      shell: kubectl taint nodes k8s-ha1 node-role.kubernetes.io/control-plane- && kubectl taint nodes k8s-ha2 node-role.kubernetes.io/control-plane- && kubectl taint nodes k8s-ha3 node-role.kubernetes.io/control-plane-